name: react-native-android-build-apk
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-apk:
    runs-on: ubuntu-latest
    env:
      QIANYU_UPLOAD_STORE_FILE: qianyu.keystore

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: ${{ !startsWith(github.ref, 'refs/tags/v') }}
          cache-cleanup: never
          cache-overwrite-existing: true
      - name: Fix Gradle wrapper permissions
        run: chmod +x android/gradlew

      - name: Decode Keystore
        run: echo "${{ secrets.QIANYU_UPLOAD_STORE_BASE64 }}" | base64 --decode > android/app/$QIANYU_UPLOAD_STORE_FILE
      - name: Create gradle.properties
        run: |
          echo "QIANYU_UPLOAD_STORE_FILE=$QIANYU_UPLOAD_STORE_FILE" >> android/gradle.properties
          echo "QIANYU_UPLOAD_KEY_ALIAS=${{ secrets.QIANYU_UPLOAD_KEY_ALIAS }}" >> android/gradle.properties
          echo "QIANYU_UPLOAD_STORE_PASSWORD=${{ secrets.QIANYU_UPLOAD_STORE_PASSWORD }}" >> android/gradle.properties
          echo "QIANYU_UPLOAD_KEY_PASSWORD=${{ secrets.QIANYU_UPLOAD_STORE_PASSWORD }}" >> android/gradle.properties

      - name: Build Android Application
        run: |
          cd android
          ./gradlew assembleRelease --no-daemon --warning-mode all --build-cache

      - name: Rename artifact
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          cd android/app/build/outputs/apk/release
          for file in *.apk; do
            mv "$file" "qianyu-$VERSION.apk"
          done

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: android/app/build/outputs/apk/release/qianyu-*.apk
