name: CI

on:
  push:
    branches:
      - main

  pull_request:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  format:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - name: Format check
        run: bun format

  lint:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - name: Lint check
        run: bun lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - name: Typecheck
        run: bun typecheck
