name: Publish
on:
  push:
    tags:
      - '@qianyu/desktop@*.*.*'
      - '@qianyu/mobile@*.*.*'
      - '@qianyu/web@*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  publish-web:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/@qianyu/web@')
    steps:
      - uses: actions/checkout@v6
      - uses: ./tools/github/actions/setup

      - name: Extract version
        run: echo "APP_VERSION=$(jq -r .version ./apps/api/package.json)" >> $GITHUB_ENV

      - name: Deploy to Production
        run: bun --filter @qianyu/infra deploy --stage prod
        env:
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          ALCHEMY_PASSWORD: ${{ secrets.ALCHEMY_PASSWORD }}
          ALCHEMY_STATE_TOKEN: ${{ secrets.ALCHEMY_STATE_TOKEN }}

          APP_VERSION: ${{ env.APP_VERSION }}
          CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}

  publish-apk:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/@qianyu/mobile@')
    env:
      APP_ROOT: apps/mobile
      RN_UPLOAD_STORE_FILE: qianyu.keystore

    steps:
      - uses: actions/checkout@v6
      - uses: ./tools/github/actions/setup

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: ${{ !startsWith(github.ref, 'refs/tags/@qianyu/') }}
          cache-cleanup: never
          cache-overwrite-existing: true
      - name: Fix Gradle wrapper permissions
        run: chmod +x $APP_ROOT/android/gradlew

      - name: Decode Keystore
        run: echo "${{ secrets.RN_UPLOAD_STORE_BASE64 }}" | base64 --decode > $APP_ROOT/android/app/$RN_UPLOAD_STORE_FILE
      - name: Config Enviroment Variables
        run: |
          echo "RN_UPLOAD_STORE_FILE=$RN_UPLOAD_STORE_FILE" >> $APP_ROOT/android/gradle.properties
          echo "RN_UPLOAD_KEY_ALIAS=${{ secrets.RN_UPLOAD_KEY_ALIAS }}" >> $APP_ROOT/android/gradle.properties
          echo "RN_UPLOAD_STORE_PASSWORD=${{ secrets.RN_UPLOAD_STORE_PASSWORD }}" >> $APP_ROOT/android/gradle.properties
          echo "RN_UPLOAD_KEY_PASSWORD=${{ secrets.RN_UPLOAD_STORE_PASSWORD }}" >> $APP_ROOT/android/gradle.properties

          echo "PUBLIC_API_URL=${{ secrets.PUBLIC_API_URL }}" >> $APP_ROOT/.env
          echo "RN_SCHEME=${{ secrets.RN_SCHEME }}" >> $APP_ROOT/.env
          echo "RN_PREFIX=${{ secrets.RN_PREFIX }}" >> $APP_ROOT/.env

      - name: Build Android Application
        run: |
          cd $APP_ROOT/android
          ./gradlew assembleRelease --no-daemon --warning-mode all --build-cache

      - name: Rename artifact
        run: |
          VERSION=${GITHUB_REF_NAME#@qianyu/mobile@}
          cd $APP_ROOT/android/app/build/outputs/apk/release
          for file in *.apk; do
            mv "$file" "qianyu-$VERSION.apk"
          done

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/@qianyu/')
        with:
          files: ${{ env.APP_ROOT }}/android/app/build/outputs/apk/release/qianyu-*.apk

  publish-desktop:
    runs-on: ${{ matrix.platform }}
    if: startsWith(github.ref, 'refs/tags/@qianyu/desktop@')
    env:
      APP_ROOT: apps/desktop
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v6
      - uses: ./tools/github/actions/setup

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libudev-dev

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Cache Rust
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Tauri Application
        run: bun --filter '@qianyu/desktop' tauri build
        env:
          VITE_API_URL: ${{ secrets.PUBLIC_API_URL }}

      - name: Rename artifact
        shell: bash
        run: |
          VERSION=${GITHUB_REF_NAME#@qianyu/desktop@}
          cd $APP_ROOT/src-tauri/target/release/bundle
          # Find and rename installer files to include the version and platform
          for file in $(find . -type f \( -name "*.dmg" -o -name "*.msi" -o -name "*.exe" -o -name "*.deb" -o -name "*.rpm" -o -name "*.AppImage" \)); do
            ext="${file##*.}"
            mv "$file" "$(dirname "$file")/qianyu-$VERSION-${{ matrix.platform }}.$ext"
          done

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/@qianyu/')
        with:
          files: |
            ${{ env.APP_ROOT }}/src-tauri/target/release/bundle/**/*.dmg
            ${{ env.APP_ROOT }}/src-tauri/target/release/bundle/**/*.msi
            ${{ env.APP_ROOT }}/src-tauri/target/release/bundle/**/*.exe
            ${{ env.APP_ROOT }}/src-tauri/target/release/bundle/**/*.deb
            ${{ env.APP_ROOT }}/src-tauri/target/release/bundle/**/*.rpm
            ${{ env.APP_ROOT }}/src-tauri/target/release/bundle/**/*.AppImage
