name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'chore(release): version packages'
          title: 'chore(release): version packages'
          version: bun .github/scripts/changeset-version.js
          publish: bun run changeset tag
          commitMode: github-api
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
